name: book_library
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  get_it: ^8.2.0
  go_router: ^16.2.4
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  shimmer: ^3.0.0
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  share_plus: ^12.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/montserrat/
    - assets/fonts/roboto/
    - assets/images/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
